from pydantic import BaseModel, Field
from typing import List, Dict, Any

# 1. Model for a single Quiz Question (Matches the structure in your assignment)
class QuizQuestion(BaseModel):
    """Defines the structure for a single question within the quiz array."""
    question: str = Field(..., description="The main text of the quiz question.")
    options: List[str] = Field(..., description="A list of exactly four possible answer options (A-D).")
    answer: str = Field(..., description="The correct answer string, which must match one of the options.")
    difficulty: str = Field(..., description="The difficulty level, one of 'easy', 'medium', or 'hard'.")
    explanation: str = Field(..., description="A short, factual explanation for the correct answer.")

# 2. Model for the LLM's full generated content
class GeneratedQuizContent(BaseModel):
    """The full structured output generated by the LLM."""
    quiz: List[QuizQuestion] = Field(..., description="A list of 5 to 10 generated quiz questions.")
    related_topics: List[str] = Field(..., description="A list of suggested Wikipedia topics for further reading based on the content.")

# 3. Model for the final API response (Combines scraped data + LLM data)
class QuizOutput(BaseModel):
    """The final structure returned by the /api/v1/questions endpoint."""
    url: str = Field(..., description="The original Wikipedia article URL.")
    title: str = Field(..., description="The title of the Wikipedia article.")
    summary: str = Field(..., description="The summary/introduction of the Wikipedia article.")
    # Assuming 'key_entities' and 'sections' are extracted in an earlier scraping step
    key_entities: Dict[str, List[str]]
    sections: List[str]
    
    # This embeds the LLM-generated content
    quiz: List[QuizQuestion]
    related_topics: List[str]